filter:
    paths: ["src"]

tools:
    external_code_coverage:
        timeout: 1200
    php_code_sniffer:
        enabled: true
        command: vendor/bin/phpcs
        config:
            standard: PSR2
        filter:
            paths: ["src"]
    php_cpd:
        enabled: true
        paths: ["src"]
    php_loc:
        enabled: true
        paths: ["src"]
    php_pdepend:
        enabled: true
        paths: ["src"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src"]