language: php

branches:
  only:
    - master
    - develop

php:
  - "5.5"
  - "5.4"

before_script:
  - composer install --dev

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover